ALTER TABLE contests
  ADD COLUMN IF NOT EXISTS location_name VARCHAR(255) DEFAULT '',
  ADD COLUMN IF NOT EXISTS location_address TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION DEFAULT NULL;
